defaults:
  - base_dataset
  - view_sampler: boundedv3
  - optional view_sampler_dataset_specific_config@view_sampler: boundedv3_dl3dv

name: dl3dv
roots: ["${oc.env:DL3DV_ROOT,./data/dl3dv}"]
test_roots: ["${oc.env:DL3DV_ROOT,./data/dl3dv}"]

input_image_shape: [224, 448]
original_image_shape: [270, 480]
cameras_are_circular: false

baseline_min: 1e-3
baseline_max: 1e2
max_fov: 100.0
