defaults:
  - base_dataset
  - view_sampler: bounded
  - optional view_sampler_dataset_specific_config@view_sampler: bounded_scannetpp

name: scannetpp
roots: ["${oc.env:SCANNETPP_IPHONE_ROOT,./data/scannetpp/iphone}"]

input_image_shape: [256, 256]
original_image_shape: [690, 920]
cameras_are_circular: false

baseline_min: 1e-3
baseline_max: 1e2
max_fov: 120.0

skip_bad_shape: false
